#!/bin/sh

export UPCHECKER_MAIL_FROM="${UPCHECKER_MAIL_FROM}"
export UPCHECKER_MAIL_TO="${UPCHECKER_MAIL_TO}"
export UPCHECKER_APPLICATION_NAME="${UPCHECKER_APPLICATION_NAME}"
export UPCHECKER_APPLICATION_URL="${UPCHECKER_APPLICATION_URL}"
export UPCHECKER_ALERT_THRESHOLD="${UPCHECKER_ALERT_THRESHOLD}"

export UPCHECKER_TIMEOUT_SEC="${UPCHECKER_TIMEOUT_SEC}"
export UPCHECKER_CRON="${UPCHECKER_CRON}"
export UPCHECKER_DEBUG="${UPCHECKER_DEBUG}"
